train_file:  ['./re_id/CUHK-PEDES/processed_data/train.json']
val_file: './re_id/CUHK-PEDES/processed_data/val.json'
test_file: './re_id/CUHK-PEDES/processed_data/test.json'
train_image_root: './re_id/CUHK-PEDES/imgs'
val_image_root: './re_id/CUHK-PEDES/imgs'
test_image_root: './re_id/CUHK-PEDES/imgs'

bert_config: 'configs/config_bert.json'

max_words: 50
image_res: 384
batch_size_train: 13
batch_size_test: 64

mlm_probability: 0.15
weak_pos_pair_probability: 0.1
mrtd_mask_probability: 0.3
queue_size: 65536
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128

alpha: 0.4
warm_up: True

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02, lr_custm: 1e-4}
schedular: {sched: cosine, lr: 1e-5, epochs: 35, min_lr: 2e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}

eval_epoch: 5


weights: {"loss_cl": 0.5, "loss_itm": 1, "loss_mlm": 1, "loss_prd": 0.5, "loss_mrtd": 0.5,"loss_sim": 0.5, "loss_itm_softmask": 1}
# 新增的权重调度配置
weights_schedule:
  freeze_epochs: 40     # 前 20 个 epoch 不变
  mode: "cosine"        # 可改为 "cosine" 获得更平滑的变化linear
  normalize_sum: false  # 若希望总权重和保持不变可改为 true
  loss_cl:
    min: 0            # 20 之后从 0.5 线性降到 0.1（到最后一个 epoch 达到）
  loss_mlm:
    max: 1.5 
  loss_itm:
    min: 0.2 
    max: 1.5

use_momentum_queue: True #是否使用动量
use_queue: False #是否使用队列
reset_queue_each_epoch: False  #每个epoch是否重置队列
enable_cl_loss: True

enable_mlm_loss:  True
saliency_compute_epoch: 99 #计算saliency的epoch
debug_mask_epoch: 10  #用来输出可视化的mask词的epoch
mlm_soft_label: False
debug_log_saliency: False  #用来输出可视化的mask词


enable_itm_loss: True
enable_itm_consistency: False
enable_itm_softmask: False

enable_infmask_loss: False


#用来控制新家的clip方案的
rationale_start_epoch: 10

# ITM rationale（mask 低贡献词）
itm_use_teacher_label: true
itm_rationale_mask_ratio: 0.5          # 每句在“有效token”里，选 bottom-ratio 置 [MASK]
itm_teacher_distill_temp: 1.0           # teacher->student 蒸馏温度
itm_teacher_hard_label: false           # false: 用 soft distill；true: teacher argmax 变 hard label

# MLM reasoning（mask 高贡献词）
mlm_use_keytoken_mask: true
mlm_keytoken_top_ratio: 0.5           # 只在 top-ratio 的高贡献词里高概率 mask
mlm_keytoken_p_other: 0.00              # 其它 token 的 mask 概率（建议 0~0.02 保持多样性）
# 维持整体 MLM mask 率的选项（可选）
mlm_keep_global_mask_rate: true         # true 时自动把 top token 的 mask 概率调到使整体约等于 mlm_probability
